name: Custom Deploy Pages
description: "Custom deploy to GitHub Pages"

inputs:
  token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - run: rm -rf deploy_dir
      shell: bash

    - run: mkdir deploy_dir
      shell: bash

    - run: cp README.md index.html deploy_dir/
      shell: bash

    - run: |
        cd deploy_dir
        git init
        git branch -m main
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy site"
        git remote add origin https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git
        git push --force origin main:gh-pages
      shell: bash
