name: Custom Upload Artifact
description: "Archive site files for deployment"
inputs:
  path:
    description: "Path to upload"
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - name: Create artifact tarball safely
      run: |
        rm -rf staging
        mkdir staging
        rsync -av --exclude='.git' --exclude='.github' --exclude='staging' ${{ inputs.path }}/ staging/
        tar -czf artifact.tar.gz -C staging .
        echo "Artifact created at artifact.tar.gz"
      shell: bash
