name: Custom Upload Artifact
description: "Archive site files for GitHub Pages"
inputs:
  path:
    description: "Path to upload"
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - name: Create artifact tarball safely
      run: |
        mkdir staging
        cp -r ${{ inputs.path }}/* staging/
        tar -czf artifact.tar.gz -C staging .
        echo "Artifact created at artifact.tar.gz"
      shell: bash
